# Generated by Django 4.0.4 on 2022-05-17 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import intmed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=200)),
                ('crm_doctor', models.IntegerField(default=0, unique=True)),
                ('email_doctor', models.EmailField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='data alocacao')),
                ('horario', models.CharField(max_length=12)),
                ('data_agendamento', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 17, 15, 41, 32, 306319, tzinfo=utc))),
                ('doctor_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intmed.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_agenda', models.DateField(validators=[intmed.models.verificarDia], verbose_name='data alocacao')),
                ('doctor_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intmed.doctor')),
            ],
        ),
    ]
