# Generated by Django 4.0.4 on 2022-05-17 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import intmed.models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0002_alter_consultas_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 17, 18, 55, 41, 395645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='horario',
            field=models.CharField(max_length=12, validators=[intmed.models.checkHorario]),
        ),
    ]
