# Generated by Django 4.0.4 on 2022-05-17 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import intmed.models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0003_alter_consultas_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_doc',
            name='dia_agenda',
            field=models.DateField(validators=[intmed.models.verificarDia, intmed.models.checkMedicoDisp], verbose_name='data alocacao'),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 17, 19, 53, 32, 153783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='dia',
            field=models.DateField(unique=True, validators=[intmed.models.verificarDia, intmed.models.checkMedicoDisp], verbose_name='data alocacao'),
        ),
    ]
