# Generated by Django 4.0.4 on 2022-05-18 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import intmed.models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0004_alter_agenda_doc_dia_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 1, 43, 13, 771019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='dia',
            field=models.DateField(unique=True, validators=[intmed.models.verificarDia], verbose_name='data alocacao'),
        ),
    ]
