# Generated by Django 4.0.4 on 2022-05-18 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0005_alter_consultas_data_agendamento_alter_consultas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 3, 9, 8, 566534, tzinfo=utc)),
        ),
    ]
