# Generated by Django 4.0.4 on 2022-05-18 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0006_alter_consultas_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 13, 52, 57, 602015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='doctor_agenda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intmed.doctor'),
        ),
    ]
