# Generated by Django 4.0.4 on 2022-05-18 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import intmed.models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0007_alter_consultas_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 14, 7, 43, 570995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='doctor_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intmed.doctor', validators=[intmed.models.checkDoctorAgendaId]),
        ),
    ]
